# Project information
site_name: Gluu Open Banking Identity Platform
site_description: Documentation for Gluu Server Open Banking Distribution

# Copyright
copyright: Copyright &copy; 2021, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-openbanking-prod
repo_url: https://github.com/GluuFederation/docs-openbanking-prod/
edit_uri: edit/1.0.0/docs/source

# Configuration
theme:
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '1.0.0'
extra_css:
  - css/tabs.css

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'

# Extensions
markdown_extensions:
- admonition
- attr_list
- toc:
     permalink: '#'
- codehilite
- pymdownx.superfences
- pymdownx.tabbed

# Navigation
nav:
- Overview: index.md
- Installation: install.md
#- Use Cases:
#    - Authorization: use-cases/authz.md
#    - CIBA: use-cases/ciba.md
#    - Consent Management: use-cases/consent.md
#    - Dynamic Client Registration: use-cases/dynamic-registration.md
#    - Identity: use-cases/identity.md
#- Operation Guide: operation.md
#- Key Management: key-management.md
#- Mutual TLS Configuration: mtls.md
#- Requirements by Country:
#    - Australia: country/australia-reqs.md
#    - Brazil: country/brazil-reqs.md
#    - Germany: country/germany-reqs.md
#    - Hong Kong: country/hk-reqs.md
#    - Japan: country/japan-reqs.md
#    - Nigeria: country/nigeria-reqs.md
#    - Singapore: country/singapore-reqs.md
#    - UK: country/uk-reqs.md
